---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls-cert
  namespace: airlock-gateway
spec:
  secretName: gateway-tls-cert
  commonName: gateway-127-0-0-1.nip.io
  dnsNames:
  - "*.nip.io"
  issuerRef:
    name: cluster-ca-issuer
    kind: ClusterIssuer
  privateKey:
    size: 4096
  usages:
  - server auth
  - digital signature
