---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/experimental-install.yaml
- gatewayclass.yaml

helmCharts:
- name: microgateway-cni
  releaseName: airlock-microgateway
  namespace: kube-system
  repo: oci://quay.io/airlockcharts
  version: 4.6.0
  valuesFile: microgateway-cni-values.yaml
- name: microgateway
  releaseName: airlock-microgateway
  namespace: airlock-microgateway-system
  repo: oci://quay.io/airlockcharts
  version: 4.6.1
  valuesFile: microgateway-values.yaml
  includeCRDs: true
