---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: juice-shop

resources:
  - contentsecuritypolicy.yaml
  - denyrule.yaml
  - headerrewrites.yaml
  - httproute.yaml
  - gateway.yaml
