---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: juice-shop

resources:
- configmap_juice_error.yaml
- contentsecuritypolicy.yaml
- customresponse.yaml
- customresponsepolicy.yaml
- denyrule.yaml
- headerrewrites.yaml
- httproute.yaml
