apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

resources:
- certificate-airlock-ca.yaml
- redis-password-secret.yaml
- redisprovider.yaml
- redis-client-cert.yaml
- sessionHandling.yaml
