---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: airlock-nextcloud-gateway
  namespace: nextcloud
spec:
  infrastructure:
    parametersRef:
      group: microgateway.airlock.com
      kind: GatewayParameters
      name: gatewayparameters
  gatewayClassName: airlock-microgateway
  listeners:
  - name: http
    port: 8080
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
