---
apiVersion: microgateway.airlock.com/v1alpha1
kind: GatewayParameters
metadata:
  name: gatewayparameters
  namespace: nextcloud
spec:
  logging:
    level: info
  kubernetes:
    service:
      type: ClusterIP
    deployment:
      replicas: 1
      placement: {}
      engineContainer: {}
      automountServiceAccountToken: false
  defaults:
    sessionHandlingRef:
      name: sessionagent
