---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

resources:
- sessionstore/
- contentsecuritypolicy.yaml
- denyrule.yaml
- gateway.yaml
- gatewayparameters.yaml
- headerrewrites.yaml
- httproute.yaml
- ingress.yaml
- limits.yaml
